### PR TITLE
closes #4280; closes #4279; closes #4276 closes #4270

### LINKED ISSUE #4270: PMID:21217703
add 
telomere end-to-end fusion  exact
NHEJ-dependent telomere fusions narrow? (although maybe always by this mechanism?)

as synonym of
circularized chromosomes

### LINKED ISSUE #4276: PMID:20089861 hcs1
decreased homocitrate synthase inhibition by L-lysine (feedback inhibition)

child of increased catalytic activity

### LINKED ISSUE #4279: PMID:32958768 NTR decreased 3' intron binding
3' intron binding

parent
FYPO:0002134 | decreased protein-RNA interaction

### LINKED ISSUE #4280: PMID:28572513
decreased ubiquitin ligase activity
child of 
FYPO:0001912 | abnormal ubiquitin ligase activity

### PR DESCRIPTION
**Pull request by ValWood**

### CODE REVIEW

**Comment by ValWood** [comment]
@manulera I'm stuck here. The checks appear to have passed but review is required. I don't see how to do this.

**Comment by ValWood** [comment]
...and the diff contains changes that I didn't make in this branch which seems odd?

**Review by manulera — APPROVED** [review]

**Comment by manulera** [comment]
Hi @ValWood:

* You can bypass the need for a review, that's what I normally do. I don't know exactly how to do it but there is something that you can select that removes the need to ask for review.
* Most of the errors are always there, I think the only "real" one is the multiple_equivalent_classes one, I can have a look.
* Regarding the diff, I don't know. It does seem that you made all those changes by looking at the "raw diff" in github.

**Comment by manulera** [comment]
You can see the raw diff here

https://github.com/pombase/fypo/pull/4284/files

**Comment by ValWood** [comment]
Yes I used the raw diff, but it's hard to read...

**Pull request merged**
