### PR TITLE
closes #4386

### LINKED ISSUE #4386: NTR for PMID:37200372
decreased vegetative cell population growth after short incubation in hydroxyurea
normal vegetative cell population growth after short incubation in hydroxyurea

### PR DESCRIPTION
**Pull request by manulera**

### CODE REVIEW

**Comment by manulera** [comment]
Hi @matentzn. I recently did the upgrade to Protege 5.6 for this repository following your instructions in #4366. I saved the file with Protege and that made a lot of changes in the formatting in https://github.com/pombase/fypo/pull/4385, as expected.

However, now I have edited the ontology in the same computer, without other changes going in, and there is a few changes in the diff that simply switch the positions of annotations of a term without making a real change, see [this PR's diff](https://github.com/pombase/fypo/pull/4387/files#diff-5ddd869d886fb89b8634e3116e8ba06c6ca13f50686e5c99443e48f3fc238166). Will this stop in the future after all inconsistencies are picked up, or is this something like the xsd_string that will happen every time we save the ontology in Protege?

cc: @ValWood

**Comment by matentzn** [comment]
I cant tell you that unfortunately @manulera - some things look odd, like you are using a wrong annotation property for your pmids in some cases (rdfs:comment instead of hasDbXref)); 

This kind of serialisation fluctuation should not generally happen! cc @anitacaron if she has an idea

**Comment by anitacaron** [comment]
I have seen this happens in other ontologies too. Somehow, Protégé doesn't apply all changes for the new serialization in the whole file. Checking the diffs, these are expected and will stop in the future.

**Comment by manulera** [comment]
Thanks both@anitacaron and @matentz for the very fast response, as usual! And thanks nico for catching that those were errors (some of my first fypo edits). I have fixed them and will do the release after the merge. Thanks!

**Comment by ValWood** [comment]
>And thanks nico for catching that those were errors (some of my first fypo edits). 

Is it possible to get error messages if we use the wrong properties. We get those with the GO pull requests is there something we need to do to make that happen?

**Comment by matentzn** [comment]
In mondo we have a strict system:

Test for permitted properties:
https://github.com/monarch-initiative/mondo/blob/master/src/sparql/qc/general/qc-permitted-properties.sparql

Test for illegal axiom annotations:
https://github.com/monarch-initiative/mondo/blob/master/src/sparql/qc/general/qc-illegal-axiom-annotation.sparql

You could adapt them to FYPO and integrate in QC!

**Pull request merged**
